// Generated from OpticalFlow.metal; host validation checks exact equality.
static const char *madeira_optical_flow_source =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"// Core begin: host tests compile these exact functions with texture adapters.\n"
"inline float of_cost(texture2d<float, access::read> a, texture2d<float, access::read> b,\n"
"                     int2 p, int2 displacement) {\n"
"    int2 limit = int2(a.get_width()-1, a.get_height()-1);\n"
"    float error = 0;\n"
"    for (int y=-4; y<=4; y+=4) for (int x=-4; x<=4; x+=4) {\n"
"        int2 q = clamp(p+int2(x,y), int2(0), limit);\n"
"        int2 r = clamp(p+int2(x,y)+displacement, int2(0), limit);\n"
"        float4 aa = a.read(uint2(q)), bb = b.read(uint2(r));\n"
"        error += (abs(aa.x-bb.x)+abs(aa.y-bb.y)+abs(aa.z-bb.z))/3;\n"
"    }\n"
"    return error/9;\n"
"}\n"
"inline float4 of_match(texture2d<float, access::read> a, texture2d<float, access::read> b, int2 p) {\n"
"    float best = 10, raw = 1;\n"
"    int2 displacement = int2(0);\n"
"    for (int y=-16; y<=16; y+=4) for (int x=-16; x<=16; x+=4) {\n"
"        float cost = of_cost(a,b,p,int2(x,y));\n"
"        float score = cost + float(abs(x)+abs(y))*0.00002;\n"
"        if (score < best) { best=score; raw=cost; displacement=int2(x,y); }\n"
"    }\n"
"    int2 coarse = displacement;\n"
"    for (int y=-2; y<=2; y++) for (int x=-2; x<=2; x++) {\n"
"        int2 d = coarse+int2(x,y);\n"
"        float cost = of_cost(a,b,p,d);\n"
"        float score = cost + float(abs(d.x)+abs(d.y))*0.00002;\n"
"        if (score < best) { best=score; raw=cost; displacement=d; }\n"
"    }\n"
"    return float4(float(displacement.x),float(displacement.y),raw,0);\n"
"}\n"
"inline bool of_confident(float4 forward, float4 backward) {\n"
"    return forward.z < 0.08 && backward.z < 0.08 &&\n"
"        length(float2(forward.x+backward.x,forward.y+backward.y)) <= 4;\n"
"}\n"
"inline float4 of_midpoint(texture2d<float, access::sample> previous, texture2d<float, access::sample> current,\n"
"                          int2 pixel, float4 forward, float4 backward) {\n"
"    if (!of_confident(forward,backward)) return current.read(uint2(pixel));\n"
"    constexpr sampler s(coord::normalized,address::clamp_to_edge,filter::linear);\n"
"    float2 size = float2(previous.get_width(),previous.get_height());\n"
"    float2 p = float2(pixel)+float2(0.5);\n"
"    float2 fromPrevious = (p-float2(forward.x,forward.y)*0.5)/size;\n"
"    float2 fromCurrent = (p-float2(backward.x,backward.y)*0.5)/size;\n"
"    return (previous.sample(s,fromPrevious)+current.sample(s,fromCurrent))*0.5;\n"
"}\n"
"// Core end\n"
"\n"
"kernel void madeira_flow(texture2d<float, access::read> previous [[texture(0)]],\n"
"                         texture2d<float, access::read> current [[texture(1)]],\n"
"                         device float4 *forward [[buffer(0)]], device float4 *backward [[buffer(1)]],\n"
"                         device atomic_uint *summary [[buffer(2)]], uint2 tile [[thread_position_in_grid]]) {\n"
"    uint columns = (previous.get_width()+15)/16, rows = (previous.get_height()+15)/16;\n"
"    if (tile.x>=columns || tile.y>=rows) return;\n"
"    int2 center = min(int2(tile*16+8),int2(previous.get_width()-1,previous.get_height()-1));\n"
"    float4 f = of_match(previous,current,center), b = of_match(current,previous,center);\n"
"    uint index = tile.y*columns+tile.x;\n"
"    forward[index]=f; backward[index]=b;\n"
"    atomic_fetch_add_explicit(summary+0,1u,memory_order_relaxed);\n"
"    atomic_fetch_add_explicit(summary+1,of_confident(f,b)?0u:1u,memory_order_relaxed);\n"
"    atomic_fetch_add_explicit(summary+2,uint((f.z+b.z)*5000),memory_order_relaxed);\n"
"}\n"
"kernel void madeira_midpoint(texture2d<float, access::sample> previous [[texture(0)]],\n"
"                             texture2d<float, access::sample> current [[texture(1)]],\n"
"                             texture2d<float, access::write> output [[texture(2)]],\n"
"                             device const float4 *forward [[buffer(0)]], device const float4 *backward [[buffer(1)]],\n"
"                             uint2 pixel [[thread_position_in_grid]]) {\n"
"    if (pixel.x>=output.get_width() || pixel.y>=output.get_height()) return;\n"
"    uint columns = (output.get_width()+15)/16;\n"
"    uint index = (pixel.y/16)*columns+pixel.x/16;\n"
"    output.write(of_midpoint(previous,current,int2(pixel),forward[index],backward[index]),pixel);\n"
"}\n"
;
